# Generated by Django 4.1.5 on 2023-02-15 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_car_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_parts',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favouriteAutoPart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='services',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favouriteService', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favouriteCar', to=settings.AUTH_USER_MODEL),
        ),
    ]
